"""add used_customer_history to draft_responses

Revision ID: 38a435c6833a
Revises: dcf794d53bf3
Create Date: 2026-08-21 12:06:03.759565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a435c6833a'
down_revision: Union[str, None] = 'dcf794d53bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_responses', sa.Column('used_customer_history', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_responses', 'used_customer_history')
    # ### end Alembic commands ###
