"""add is_lead to tickets

Revision ID: dcf794d53bf3
Revises: b8e2f4a91c67
Create Date: 2026-08-21 11:40:45.994824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf794d53bf3'
down_revision: Union[str, None] = 'b8e2f4a91c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_lead', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'is_lead')
    # ### end Alembic commands ###
